
abstract=
ontologyTitle=Example Ontology
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=http://example.org/def/base#
ontologyName=Example Ontology
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.0.2
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=Víctor Cabezas. Example Ontology. Revision: 0.0.2.
DOI=
status=Ontology Specification Draft
logo=
description=
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Víctor Cabezas
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
